apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp
  labels:
    app: gowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gowebapp
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
      - name: gowebapp
        image: lalitkr2526/gowebapp:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
